spring:
  data:
    mongodb:
      database: ${MONGO_DATABASE:foodey}
      uri: mongodb+srv://${MONGO_USER:admin}:${MONGO_PASSWORD}@foodey.jdbhlen.mongodb.net/?retryWrites=true&w=majority&appName=Foodey
      autoIndexCreation: true
  profiles:
    active: prod

logging:
  file:
    name: logs/foodey.log

foodey:
  jwt:
    secret-key: 01fbe13122a008e71d1f60b9fe9d1df3c3532845de0d3312bf04eee066be7f87 # FOODEY_JWT_SECRET_KEY
    access-token-expiration: 300000 # 5 mins
    refresh-token-expiration: 2592000000 # 30 days
  sms:
    httpsms:
      api-key: Z1CRFGp2xy2Pww71MTfImM8ikzpNHiEjYGGXoXBB1Bz7gOYTGSCrg_uszlIQr0zd
      sender: "+84392211343"
  otp:
    expiration:
      high: 600000 # 10 mins
      medium: 300000 # 5 mins
      short: 60000 # 1 min
      fast: 30000 # 30s
    resend-interval: 60000 # 1 min

    # OTP SMS Configuration
twilio:
  account:
    sid: AC25441bcc1850e3589856409215753922
  auth:
    token:
      cc529a66b93f144a7ad2d9fb2607f48e
      #
# twilio.account.sid=AC8adc8fd23169086c030a75fc218565c1
# twilio.auth.token=c247d698778e1c3d0bed4016945f4bf2
# twilio.trial.number=+12058925316
# twilio.path-service-sid=VAdd009209f87e4bad1db116b3e7b4f8ae

